# Generated by Django 3.1.7 on 2021-03-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artists_ratings_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
