# Generated by Django 3.1.7 on 2021-03-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210315_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='song',
            field=models.TextField(),
        ),
    ]
